// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, KvCache, Logger, MRNObject, ServiceStub, SmartBucket, SmartMemory, SmartSql, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  API_GATEWAY: ServiceStub<import('../api-gateway/index.js').default>;
  ARTIST_DATA_BUCKET: SmartBucket;
  AUTH_SERVICE: ServiceStub<import('../auth-service/index.js').default>;
  CONVERSATION_MEMORY: SmartMemory;
  DATA_ENRICHMENT_SERVICE: ServiceStub<import('../data-enrichment-service/index.js').default>;
  DISCOGS_API_KEY: string;
  EMAIL_API_KEY: string;
  EMAIL_FROM_ADDRESS: string;
  EMAIL_SERVICE: ServiceStub<import('../email-service/index.js').default>;
  FRONTEND_URL: string;
  JWT_SECRET: string;
  LISTENING_EXPERIENCE_SERVICE: ServiceStub<import('../listening-experience-service/index.js').default>;
  logger: Logger;
  MAIN_DATABASE: SmartSql;
  mem: KvCache;
  PORTRAIT_SERVICE: ServiceStub<import('../portrait-service/index.js').default>;
  RECOMMENDATION_SERVICE: ServiceStub<import('../recommendation-service/index.js').default>;
  SESSION_SERVICE: ServiceStub<import('../session-service/index.js').default>;
  SPOTIFY_CLIENT_ID: string;
  SPOTIFY_CLIENT_SECRET: string;
  SPOTIFY_INTEGRATION_SERVICE: ServiceStub<import('../spotify-integration-service/index.js').default>;
  SPOTIFY_REDIRECT_URI: string;
  tracer: Tracer;
}
